spring:
  application:
    name: project_six
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/project_six
    username: bridge_user
    password: p@ssw0rd

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080